### ISSUE TITLE
DNF daemon not recognize any 3rd party repository other than official Fedora repositories !

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdaemon#28]
Hi. Since Fedora received DNF till now Dnfdragora does not recognize any 3rd party repositories. It recognizing only Fedora repositories ! 

RPMFusion repositories not recognized. Other 3rd party repositories like that of Jami or Retroshare also not recognized !

When I say "not recognized" I mean when new update reach for Fedora package, then dnfdragora notify about this new update. But if package(s) in RPMFusion repositories receive update then dnfdragora not recognize this ! Also when user search about 3rd party repository package by "Alt+S" within dnfdragora search result will either not show package(s) or show it(they) at last line ......

I opened bug about this in dnfdragora GitHub since long time & developer said that this is dnf daemon issue not dnfdragora issue. But since that too long time till now no fix done ! For that I open this issue here.

Kindly your attention.

**Comment by Nokia808** [comment]
Hi. why there is no any progression in this thread after all these months ?! This issue make dnfdragora functionless from many aspect ... What is the point to install a program supposed to be a package manager but it show only half of  used repositories ?? I'm already removed dnfdragora from my system since long time because no fix for this bug ...

**Comment by anaselli** [comment]
are you sure? dnfdragora 2.0.x has introduced the update concept also to new version to install that yumex-dnf had not, so that is fixed since 2.0.0.
Tryed with skypeforlinux, megasync and rpmfusion

**Comment by Nokia808** [comment]
@anaselli 
Why leave this issue opened all this time after you are already fix it !! Moreover, you did not documented this fix in change log of version 2.0.0 ! How user can know that this is fixed !

I will check if Fedora start to work on version 2.0.3 Just when this release or higher will become available to me, I will installed dnfdragora again & give you feedback ...

**Comment by anaselli** [comment]
Maybe because of the vocie "Massively reworked dnfdragora to be async and more reliable"
Too many for documenting, but you can look at commits and help us to write release notes.  
And the reasons why these bugs remain open is that often people don't answer if they are fixed or not and then developer should do extra work to recall if they were.
Waiting for Fedora version 2.0.4 does not help us in fixing other bugs or finding new ones, but i see your point, so please just understand ours. Thank you
